version: 0.0
os: windows
files:
  - source: /
    destination: C:/inetpub/wwwroot/DemoGIt
hooks:
   BeforeInstall:
     - location: DemoGit/appstop.bat       
       runas: administrator
   ApplicationStart:
     - location: DemoGit/appstart.bat       
       runas: administrator
